DROP TABLE IF EXISTS public.orders;
CREATE TABLE public.orders (
"order_id"   TEXT,
  "customer_id" TEXT,
  "order_status" TEXT,
  "order_purchase_timestamp" TIMESTAMP,
  "order_approved_at" TIMESTAMP,
  "order_delivered_carrier_date" TIMESTAMP,
  "order_delivered_customer_date" TIMESTAMP,
  "order_estimated_delivery_date" TIMESTAMP,
  "purchase_date" DATE,
  "payment_total_credit_card" REAL,
  "number_of_payments_credit_card" INTEGER,
  "number_of_installments_credit_card" INTEGER,
  "payment_total_sum" REAL,
  "main_payment_type" TEXT,
  "_merge_payments" TEXT,
  "seller_id" TEXT,
  "total_price" REAL,
  "total_freight" REAL,
  "n_items" INTEGER,
  "gross_order_value" REAL,
  "_merge_items" TEXT,
  "residual" REAL,
  "customer_unique_id" TEXT,
  "customer_zip_code_prefix" INTEGER,
  "customer_city" TEXT,
  "customer_state" TEXT,
  "seller_zip_code_prefix" INTEGER,
  "seller_city" TEXT,
  "seller_state" TEXT,
  "payment_total_boleto" REAL,
  "payment_total_debit_card" REAL,
  "payment_total_voucher" REAL,
  "payment_total_not_defined" REAL,
  "number_of_payments_boleto" INTEGER,
  "number_of_payments_debit_card" INTEGER,
  "number_of_payments_voucher" INTEGER,
  "number_of_payments_not_defined" INTEGER,
  "order_ranking" INTEGER,
  "order_ranking_delivered" INTEGER,
  "order_at_seller_ranking_delivered" INTEGER,
  "days_from_last_order" INTEGER,
  "month_from_last_order" INTEGER
);




DROP TABLE IF EXISTS staging.orders;
CREATE TABLE staging.orders (
"order_id"  TEXT,
  "customer_id" TEXT,
  "order_status" TEXT,
  "order_purchase_timestamp" TIMESTAMP,
  "order_approved_at" TIMESTAMP,
  "order_delivered_carrier_date" TIMESTAMP,
  "order_delivered_customer_date" TIMESTAMP,
  "order_estimated_delivery_date" TIMESTAMP,
  "purchase_date" DATE,
  "payment_total_credit_card" REAL,
  "number_of_payments_credit_card" INTEGER,
  "number_of_installments_credit_card" INTEGER,
  "payment_total_sum" REAL,
  "main_payment_type" TEXT,
  "_merge_payments" TEXT,
  "seller_id" TEXT,
  "total_price" REAL,
  "total_freight" REAL,
  "n_items" INTEGER,
  "gross_order_value" REAL,
  "_merge_items" TEXT,
  "residual" REAL,
  "customer_unique_id" TEXT,
  "customer_zip_code_prefix" INTEGER,
  "customer_city" TEXT,
  "customer_state" TEXT,
  "seller_zip_code_prefix" INTEGER,
  "seller_city" TEXT,
  "seller_state" TEXT,
  "payment_total_boleto" REAL,
  "payment_total_debit_card" REAL,
  "payment_total_voucher" REAL,
  "payment_total_not_defined" REAL,
  "number_of_payments_boleto" INTEGER,
  "number_of_payments_debit_card" INTEGER,
  "number_of_payments_voucher" INTEGER,
  "number_of_payments_not_defined" INTEGER,
  "order_ranking" INTEGER,
  "order_ranking_delivered" INTEGER,
  "order_at_seller_ranking_delivered" INTEGER,
  "days_from_last_order" INTEGER,
  "month_from_last_order" INTEGER
);