DROP SCHEMA  IF EXISTS "staging" CASCADE;
CREATE SCHEMA "staging";


DROP SCHEMA IF EXISTS "public" CASCADE;
CREATE SCHEMA "public";


DROP SCHEMA IF EXISTS "datamart" CASCADE;
CREATE SCHEMA "datamart";